//
//  SearchResultPresenterTests.swift
//  NGMusic
//
//  Created by Deepak on 06/08/22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

@testable import NGMusic
import XCTest

private class SearchResultDisplayLogicSpy: SearchResultDisplayLogic {
    var showResultCalled = false
    func showResult(items: [[MusicResponseModel]], types: [String]) {
        showResultCalled = true
    }
}

class SearchResultPresenterTests: XCTestCase {
  var sut: SearchResultPresenter!

  override func setUp() {
    super.setUp()
    setupSearchResultPresenter()
  }

  override func tearDown() {
    super.tearDown()
  }

  func setupSearchResultPresenter() {
    sut = SearchResultPresenter()
  }

  func testPresentSomething() {
    let spy = SearchResultDisplayLogicSpy()
    sut.viewController = spy
    sut.showResult(items: [[]], types: ["Album"])
    XCTAssertTrue(spy.showResultCalled, "showResult should ask the view controller to display the result")
  }
}
