//
//  SearchResultInteractorTests.swift
//  NGMusic
//
//  Created by Deepak on 06/08/22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

@testable import NGMusic
import XCTest

private class SearchResultPresentationLogicSpy: SearchResultPresentationLogic {
    var updateMusicCalled = false
    func showResult(items: [[MusicResponseModel]], types: [String]) {
        updateMusicCalled = true
    }
}
class SearchResultInteractorTests: XCTestCase {
  var sut: SearchResultInteractor!

  override func setUp() {
    super.setUp()
    setupSearchResultInteractor()
  }

  override func tearDown() {
    super.tearDown()
  }

  func setupSearchResultInteractor() {
    sut = SearchResultInteractor()
  }

  func testUpdateMusic() {
    let spy = SearchResultPresentationLogicSpy()
    sut.presenter = spy
    sut.updateMusic()
    XCTAssertTrue(spy.updateMusicCalled, "updateMusic(request:) should ask the presenter to format the result")
  }
}
